---
- name: yarn install locally
  connection: local
  command: yarn install
  args:
    chdir: ../frontend
- name: build frontend locally
  connection: local
  command: yarn build
  args:
    chdir: ../frontend
- name: push frontend
  copy:
    src: ../../../../frontend/dist
    dest: "{{root_dir}}/frontend"
